fix(pipeline): Update SonarCloud project provisioning

diff --git a/github/nodejs/node-express/template/.github/workflows/pipeline.yaml b/github/nodejs/node-express/template/.github/workflows/pipeline.yaml
--- a/github/nodejs/node-express/template/.github/workflows/pipeline.yaml
+++ b/github/nodejs/node-express/template/.github/workflows/pipeline.yaml
@@ -101,51 +101,45 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Check if SonarCloud Project Exists and Provision if Necessary
+      - name: Check if SonarCloud Project Exists
         id: sonarcloud-check
         run: |
           repo_name=$(echo "${{ github.repository }}" | sed 's/.*\///')
           organization="${{ secrets.SONAR_ORG }}"
-          installation_key="github.com/${{ github.repository }}"
 
           # Search for the project in SonarCloud
           response=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-            "https://sonarcloud.io/api/projects/search?organization=${organization}&projects=${repo_name}")
+            "https://sonarcloud.io/api/projects/search?projects=${repo_name}&organization=${organization}")
 
           project_exists=$(echo "$response" | jq '.paging.total')
           if [ "$project_exists" -eq 0 ]; then
-            echo "SonarCloud project does not exist. Provisioning project..."
+            echo "SonarCloud project does not exist. Creating project..."
 
-            # Provision the project in SonarCloud with ALM binding
-            provision_response=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
-              "https://sonarcloud.io/api/alm_integration/provision_projects" \
+            # Create the project in SonarCloud
+            create_response=$(curl -s -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+              "https://sonarcloud.io/api/projects/create" \
               -d "organization=${organization}" \
-              -d "installationKeys=${installation_key}")
+              -d "name=${repo_name}" \
+              -d "project=${repo_name}")
 
-            # Check if the project was provisioned successfully
-            errors=$(echo "$provision_response" | jq '.errors')
-            if [ "$errors" != "null" ]; then
-              echo "Failed to provision SonarCloud project. Response:"
-              echo "$provision_response"
-              exit 1
+            # Check if the project was created successfully
+            status=$(echo "$create_response" | jq -r '.project.key')
+            if [ "$status" == "$repo_name" ]; then
+              echo "SonarCloud project created successfully."
             else
-              echo "SonarCloud project provisioned successfully."
+              echo "Failed to create SonarCloud project. Response:"
+              echo "$create_response"
+              exit 1
             fi
           else
             echo "SonarCloud project already exists."
           fi
 
-
-
       # - name: Run tests with coverage
       #   run: npm run test:cov
 
-      - name: Run SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@v2
-        with:
-          args: >
-            -Dsonar.organization=${{ secrets.SONAR_ORG }}
-            -Dsonar.projectKey=${{ secrets.SONAR_ORG }}_${{ github.repository }}
+      - name: Run Static Analysis (SonarCloud)
+        uses: SonarSource/sonarcloud-github-action@master
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
